### ISSUE TITLE
Binding conflicts with new magit-merge-into

### ISSUE THREAD

**Issue by tarsius** [magit/magit-imerge#2]
By default `i` is now bound to `magit-merge-into` in the merge popup. How about binding `I` to `magit-imerge-popup`?

**Comment by kyleam** [comment]
> By default `i` is now bound to `magit-merge-into` in the merge popup.

Thanks.  I should have realized that when magit-merge-into was added.

> How about binding `I` to `magit-imerge-popup`?

Sure, I'll do that.

**Comment by npostavs** [comment]
I found <kbd>m I i</kbd> for `magit-imerge-continue` pretty awkward. I ended up binding `magit-imerge-popup` to <kbd>i</kbd> since I don't use `magit-gitignore` very much. Since both <kbd>i</kbd> and <kbd>I</kbd> are ignore commands, maybe they could move to a popup to free one of those up?

**Comment by tarsius** [comment]
I never use `magit-gitignore` and two of the rare keys for this sort of thing is quite a waste I agree. I am packing for a flight and will get back to this in a few days. (Ping me eventually if I forget about it.)

**Comment by tarsius** [comment]
> maybe they could move to a popup to free one of those up?

https://github.com/magit/magit/compare/i-for-imerge?expand=1

We could also leave the <kbd>i</kbd> binding intact. Similar to how `magit-revert-no-commit` is available from both <kbd>v</kbd> and <kbd>V v</kbd>.

`magit-imerge.el` could override <kbd>i</kbd> unconditionally or only suggest that the user bind that to the imerge popup.

**Comment by npostavs** [comment]
> `magit-imerge.el` could override <kbd>i</kbd> unconditionally or only suggest that the user bind that to the imerge popup.

On the one hand, I want to say that it would make the most sense if imerge only takes over <kbd>i</kbd> while performing an imerge. On the other hand, I fear it would be too confusing.

**Comment by kyleam** [comment]
>> maybe they could move to a popup to free one of those up?
>
> https://github.com/magit/magit/compare/i-for-imerge?expand=1
>
> We could also leave the <kbd>i</kbd> binding intact. Similar to how `magit-revert-no-commit` is available from both <kbd>v</kbd> and <kbd>V v</kbd>.
>
> `magit-imerge.el` could override <kbd>i</kbd> unconditionally or only suggest that the user bind that to the imerge popup.

I feel a little be uneasy about imerge taking a rare top-level, lower-case key.  I'd guess it has about five users :/  If <kbd>i</kbd> were left intact, though, I suppose it's not bad, because then just imerge users would be affected.

I was considering <kbd>m I I</kbd> (i.e. bind `magit-imerge-continue` to <kbd>I</kbd>).  I guess the main downside is that, if a user did want to bind `magit-imerge-popup` to <kbd>i</kbd>, they'd also have to rebind `magit-imerge-continue` to avoid <kbd>i I</kbd>.

I suppose at this point I'd vote for leaving <kbd>i</kbd> intact, making <kbd>I</kbd> a popup, and having imerge unconditionally bind <kbd>i</kbd>.

> On the one hand, I want to say that it would make the most sense if imerge only takes over <kbd>i</kbd> while performing an imerge. On the other hand, I fear it would be too confusing.

I also worry that'd be too confusing.
